# 1日の長さ（例：24000で通常の長さ、48000なら半分の速さで1日が進む）
dayLength: 48000

# サーバーの役割：trueならこのサーバーがマスター。falseならスレーブ
isMaster: true

# 同期する間隔（秒）
syncInterval: 30

# マスターが待ち受けるポート番号
syncPort: 5000

# スレーブが接続するマスターのホスト名
syncHost: "100.76.121.124"